Files added
Ayush-kumar1/E-commerce-frontend-final-submission pull request #1
Opened 2021-05-06 11:56 UTC by Ayush-kumar1

This is the frontend for the e-commerce app version 1.Pls review it

2021-05-06 14:06 UTC, asmitzz requested changes

2021-05-06 14:06 UTC, asmitzz commented on src/App.js
> +    //   <Header/>
remove commented code

2021-05-06 14:06 UTC, asmitzz commented on src/Context/CartContext.jsx
> +    // const [itemsinCart, setItemsinCart]=useState([])
remove commented code

2021-05-06 14:06 UTC, asmitzz commented on src/Context/CartContext.jsx
> +         getData();
use trycatch block here

2021-05-06 14:06 UTC, asmitzz commented on src/DemoProduct/DemoProduct.css
> +    max-height: 400px;
avoid pixels

2021-05-06 14:06 UTC, asmitzz commented on src/DemoProduct/DemoProduct.css
> +.product>img {
made class of image inside .product and then apply css

2021-05-06 14:06 UTC, asmitzz commented on src/DemoProduct/DemoProduct.jsx
> +    // const addToBasket=()=>{
remove commneted code

2021-05-06 14:07 UTC, asmitzz commented
fixed netlify 404 broken link issue

2021-05-06 14:07 UTC, asmitzz commented
display the number of items present in the cart and wishlist on the home page

2021-05-06 14:09 UTC, asmitzz commented
when I click on add to cart then put a condition if product is added in the cart then go to cart option will show there otherwise same product will add multiple times in the cart

2021-05-06 14:10 UTC, asmitzz commented
In the cart page disable the button when the quantity of product will be 1 or more then one

2021-05-06 14:11 UTC, asmitzz commented
add cursor:pointer property on all the buttons

2021-05-06 17:46 UTC, jugalkpatel commented
add deployed site link in about section.

2021-05-06 17:47 UTC, jugalkpatel commented on src/index.js
> +
remove spaces here.

2021-05-06 17:51 UTC, jugalkpatel commented on src/SingleContent/SingleContent.jsx
> +             <img className="poster" src={image} alt=""/>
add text in the alt attribute.

2021-05-06 18:00 UTC, jugalkpatel commented on src/Header/Header.jsx
> +import "./Header.css"
header is overlapping landing page content.

2021-05-06 18:00 UTC, jugalkpatel commented on src/Header/Header.jsx
> +            <img src={logo1} className="logo" alt="" />
add text to alt attribute.

2021-05-06 18:01 UTC, jugalkpatel commented on src/Header/Header.jsx
> +           {/* <div>
remove unnecessary lines.

2021-05-06 18:02 UTC, jugalkpatel commented on src/DemoProduct/DemoProduct.css
> +    background: #f0c14b;
add color to variables.

2021-05-06 18:03 UTC, jugalkpatel commented on src/DemoProduct/DemoProduct.css
> +    background: #f0c14b;
add color to variables.

2021-05-06 18:06 UTC, jugalkpatel commented on src/DemoProduct/DemoProduct.jsx
> +            <img className="demo_image"  src={image} alt=""/>
add text to alt attribute.

2021-05-06 18:06 UTC, ardourApeX commented
- Wishlist page is getting broken. Please check: Add to wishlist -> Go to wishlist page -> Click on Remove from Wishlist.
Now there won't be any header and if you refresh the page it gets broken.

2021-05-06 18:07 UTC, joyguptaa commented on src/Pages/Home/Home.jsx
> +            <img className="home_img" src="https://images-eu.ssl-images-amazon.com/images/G/31/img21/Fashion/Gateway/SuperSale_Herotator_1st-3rdMar/Rev_FST_GW_PC_BUNK_1500x600._CB655793405_.jpg" alt=
The image is not responsive.

2021-05-06 18:07 UTC, ardourApeX commented on src/Pages/Cart/Cart.jsx
> +                    <button onClick={()=> dispatch({type: "DECREMENT", payload: elem._id})}> -- </button>
It should remove the item from the cart when its count goes below 1.

2021-05-06 18:17 UTC, jugalkpatel commented
app became blank while removing item from wishlist page.
see this
https://shareit.video/TEFYfdieOSryLCyBBYf3

2021-05-06 18:18 UTC, jugalkpatel commented
quantity and amount are going into minus.
![image](https://user-images.githubusercontent.com/39916455/117346590-9108de80-aec5-11eb-8259-15aae726cfad.png)

2021-05-06 18:25 UTC, jugalkpatel commented
- make code formatting better.
- remove unnecessary spaces.
- add count on cart and wishlist icons.
- fix cart duplication and add remove from cart button

Suggestions:

- add clear all filters button.
- show total products count on product listing page.

2021-07-07 15:03 UTC, thesudeshdas requested changes
Look into your folder structure

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Login/Login.jsx
> +              {" "}
Why the space?

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Signup/Signup.jsx
> +            type="text"
The type should be password here

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Signup/Signup.jsx
> +import React, { useState,useEffect } from "react";
When I signed up, the async call was made, but by that time, I clkicked in sign up 2 more times. Make a loader to let user know that he is being signed up, and he should wait.
![Screenshot from 2021-07-07 19-48-48](https://user-images.githubusercontent.com/65083809/124775822-91bd0000-df5c-11eb-96a4-4c1b10688983.png)

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Header/Header.jsx
> +        <div className="nav">
The whole navbar has cursor pointer. It should only be on the links

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Header/Header.jsx
> +             <div style={{display:"flex",gap:"1rem",paddingTop:"1rem"}}>
This div is not aligned vertically properly, align it to center?

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Wishlist/Wishlist.jsx
> +        ? <h2>You cart is empty</h2>
It should be "Your wishlist is empty"

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Header/Header.jsx
> +                     <Link to="/login">
If I am already logged in, Why should I be redirected to the login page again? Shouldn't this either give the account details or give me an option to log out?

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Home/Home.jsx
> +        <button className="product_button">BROWSE PRODUCT</button>
Give this button a cursor: pointer

2021-07-07 15:03 UTC, thesudeshdas commented on src/App.js
> +import "./App.css";
The app breaks on reload

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Product/Product.jsx
> +            <h2>Ratings</h2>
products list not changing on the selected rating

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Product/Product.jsx
> +             <label>
Both the options should be checkable simultaneously

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Product/Product.jsx
> +      <div className="sidenav">
Create sidenav as a separate component

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Product/Product.jsx
> +            return (
Make card cursor: pointer

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Product/Product.jsx
> +                <img
Give image height, width. [Object-fit: cover](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Product/Product.jsx
> +                    <FavoriteIcon color="inherit" />
If product is successfully added to the wishlist, change the color of the icon

2021-07-07 15:03 UTC, thesudeshdas commented on src/Components/Cart/Cart.jsx
> +                          <AddIcon onClick={() => incrementer(elem._id)} />
plus icon on the right, minus on the left

2021-07-07 15:03 UTC, thesudeshdas commented on public/index.html
> +    <title>React App</title>
Change the title with change in page url & use favicon

2021-07-10 14:59 UTC, merged